spring:
  profiles:
    active: ${catalogServiceAppProfile}
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${catalogServiceAppMongoURI}
      database: ${catalogServiceAppMongoDbName}

server:
  servlet:
    context-path: /catalog_service
  port: ${catalogServiceAppPort}
