spring:
  profiles:
    active: ${catalogServiceAppProfile}
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${catalogServiceAppMongoURI}
      database: ${catalogServiceAppMongoDbName}
kafka:
  bootstrap-servers: ${kafkaBootstrapServers}
  topic:
    product: ${productTopic}
    brand: ${brandTopic}
    category: ${categoryTopic}

server:
  servlet:
    context-path: /catalog_service
  port: ${catalogServiceAppPort}
---
spring:
  profiles:
    active: prod
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
