package dev.lokeshbisht.catalogservice.enums;

public enum ErrorCode {
  AUTHENTICATION_ERROR,
  AUTHORIZATION_ERROR,
  BAD_REQUEST,
  BRAND_ALREADY_EXISTS,
  INTERNAL_SERVER_ERROR,
  PRODUCT_ALREADY_EXISTS,
  PRODUCT_NOT_FOUND,
}
